resolver: lts-13.10
flags: {}

packages:
  - .
extra-deps:
  - github: cmk/property
    commit: 8c6527acfc44af301190a3bbbc7c36b33a9b4fc1
  - github: cmk/connections
    commit: a45bdf0483cc7f8e06b21a7d872ccb04877ffc38
